version: "3.9"
services:
  app-dev:
    build:
      context: .
      dockerfile: DockerFile-dev
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  app-prod:
    build:
      context: .
      dockerfile: DockerFile-prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
