version: "3.9"
services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      MONGODB_URI: "mongodb://mongoDB:27017/mamaputDB"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - mongoDB
    networks:
      - app-network

  mongoDB:
    image: mongo:5.0
    container_name: mamaputDB
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
