version: "3.9"
services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules  # Prevent overwriting container's node_modules with host files
    restart: unless-stopped

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
